sonar.projectKey=sistema-venta-entradas-frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,node_modules/**,.angular/**,dist/**
sonar.coverage.exclusions=src/**/*.spec.ts,src/main.ts,src/environments/**,src/app/core/services/firebase-auth.service.ts,src/app/features/tickets/validate-entry/validate-entry.component.ts,src/app/features/tickets/validate-food/validate-food.component.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
