sonar.projectKey=sistema-ventas-entradas-backend
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go,cmd/**,tools/**,internal/database/**,internal/repository/**,internal/routes/**
sonar.go.coverage.reportPaths=coverage.out
